### ISSUE TITLE
This should be a go package rather than an application in itself.

### ISSUE THREAD

**Issue by swarupdonepudi** [jgensler8/go-sysdig#1]
This is more of a feature request than a bug/issue. But I do not know how to create a feature request on GitHub.

**Comment by jgensler8** [comment]
I believe this is a Go package. The source code in this repo was generated from:
* https://app.swaggerhub.com/apis/jgensler8/sysdig/1.0.0

In my experience, Swagger creates a "Default API" class/object/service depending on language and framework. This is what you as your "SDK" for a REST service. Here are the relevant lines for this repository: https://github.com/jgensler8/go-sysdig/blob/431b26106c5e5d667441b6de2c6bc83fabe804f3/default_api.go#L32-L59

Side Note: If it is helpful, you can track progress on why I've started this project here: https://github.com/draios/python-sdc-client/issues/20
